server {
  listen 80;
  
  location / {
    # Root path for static site content.
    root /usr/share/nginx/html;

    # SPA/Blazor routing:
    # - Serve a file if it exists.
    # - Otherwise fall back to index.html.
    try_files $uri $uri/ /index.html =404;
  }

  # Redirecting backend traffic
  location /api/ {
    proxy_pass http://asbnapp-api:8080/api/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
  }
}
