server {
  listen 80;
  
  location / {
    # Root path for static site content.
    root /usr/share/nginx/html;

    # SPA/Blazor routing:
    # - Serve a file if it exists.
    # - Otherwise fall back to index.html.
    try_files $uri $uri/ /index.html =404;
  }

  # Redirecting backend traffic
  location /api/ {
    proxy_pass ${API_PROXY_PASS_URL};
    proxy_http_version 1.1;
  }
}
