# On creating a new release, publish new container images for front and backend.

name: Publish new Release

on:
  release:
    types: [published]

jobs:
  publish-release-images:
    name: Publish Release Images
    uses: ./.github/workflows/publish-docker.yml
    with:
      stage: release
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
          